
let prompts = [
    'New York streetscape',
    'Endless Library of Babel',
    'Hyperlapse',
    'Starfield',
    'Cartographic map',
    'Atomic nuclei',
    'Oceanographic charts',
    'Galaxy Cluster',
    'Mandelbrot Fractal',
    'Microscopic Cellular Structure',
    'Cityscape at Night',
    'Coral Reef Ecosystem',
    'Circuit Board Patterns',
    'Neural Network Visualization',
    'Ant Colony',
    'Time-lapse of Growing Plants',
    'Deep Ocean Trench',
    'Snowflake Crystal Structure',
    'Urban Traffic Flow',
    'Solar System Orbits',
    'Data Visualization of Global Internet Traffic',
    'Abstract Artwork',
    'Dense Forest Canopy',
    'Architectural Blueprint',
    'Lunar Surface',
    'Time-lapse of a Flower Blooming',
    'Mechanical Watch Movement',
    'Underwater Caves',
    'Firework Burst',
    'Aurora Borealis',
    'Digital Circuit Microchip',
    'Insect Wing Microstructure',
    'Jungle Canopy Aerial View',
    'City Subway System Map',
    'Volcanic Crater Landscape',
    'Digital Hologram Projection',
    'Binary Code Matrix',
    'Geological Cross-section',
    'Fingerprint Patterns',
    'Futuristic Cyberspace Matrix',
    'DNA Double Helix',
    'Satellite View of Earth at Night',
    'Abstract Soundwave Visualization',
    'Artificial Intelligence Network',
    'Bonsai Tree Detailed Branches',
    'Colorful Paint Palette',
    'Retro Vinyl Record Grooves',
    'Starry Night Sky',
    'Intricate Mandala Design',
    'Carnival Ferris Wheel Lights',
    'Steam Locomotive Engine',
    'Human Eye Iris',
    'Glowing Fireflies in a Meadow'
]

export default async function handler(req, res) {
    let prompt = prompts[Math.floor(Math.random() * prompts.length)]
    res.statusCode = 201;
    res.end(JSON.stringify(prompt));
}
