
let prompts = [
    'New York streetscape',
    'Endless Library of Babel',
    'Hyperlapse',
    'Starfield',
    'Cartographic map',
    'Atomic nuclei',
    'Oceanographic charts',
    'Galaxy Cluster',
    'Mandelbrot Fractal',
    'Microscopic Cellular Structure',
    'Cityscape at Night',
    'Coral Reef Ecosystem',
    'Circuit Board Patterns',
    'Neural Network Visualization',
    'Ant Colony',
    'Time-lapse of Growing Plants',
    'Deep Ocean Trench',
    'Snowflake Crystal Structure',
    'Urban Traffic Flow',
    'Solar System Orbits',
    'Data Visualization of Global Internet Traffic',
    'Abstract Artwork',
    'Dense Forest Canopy',
    'Architectural Blueprint',
    'Lunar Surface',
    'Time-lapse of a Flower Blooming',
    'Mechanical Watch Movement',
    'Underwater Caves',
    'Firework Burst',
    'Aurora Borealis',
    'Digital Circuit Microchip',
    'Insect Wing Microstructure',
    'Jungle Canopy Aerial View',
    'City Subway System Map',
    'Volcanic Crater Landscape',
    'Digital Hologram Projection',
    'Binary Code Matrix',
    'Geological Cross-section',
    'Fingerprint Patterns',
    'Futuristic Cyberspace Matrix',
    'DNA Double Helix',
    'Satellite View of Earth at Night',
    'Abstract Soundwave Visualization',
    'Artificial Intelligence Network',
    'Bonsai Tree Detailed Branches',
    'Colorful Paint Palette',
    'Retro Vinyl Record Grooves',
    'Starry Night Sky',
    'Carnival Ferris Wheel Lights',
    'Steam Locomotive Engine',
    'Human Eye Iris',
    'Glowing Fireflies in a Meadow',
    'Glowing Jellyfish Bioluminescence',
    'Solar Flare Eruption',
    'Abstract Kaleidoscope Patterns',
    'Underground Cave Stalactites',
    'Amusement Park Roller Coaster',
    'Digital Encryption Key',
    'Macro Water Droplets on a Leaf',
    'The Rings of Saturn',
    'Subatomic Particle Collision',
    'Vintage Pocket Watch Mechanism',
    'Spiral Galaxy Formation',
    'Abstract Colorful Smoke Patterns',
    'Crystal Growth Microstructure',
    'Holographic 3D Chessboard',
    'Synchronized Swimming Performance',
    'The Great Wall of China Aerial View',
    'Topographic Mountain Range',
    'Retro Arcade Game Pixel Art',
    'Vivid Hot Air Balloon Festival',
    'Ballet Dancer in Mid-Air Leap',
    'Microbial Life in a Petri Dish',
    'Abstract Stained Glass Window',
    'Rainforest Canopy',
    'Wind Turbine Farm Aerial',
    'Glacier Ice Cave Interior',
    'Futuristic City Skyline',
    'Electric Guitar Fretboard Close-up',
    'Nebula Cloud in Deep Space',
    'Digital Virtual Reality Landscape',
    'Sailing Ship Rigging Details',
    'Hexagonal Honeycomb Pattern',
    'Abstract Cyberpunk Cityscape',
    'Macro Circuitry Board',
    'Bioluminescent Mushrooms in a Forest',
    'Diverse Human DNA Sequencing',
    'Sunflower Seed Head Microstructure',
    'Dynamic Concert Crowd',
    'Abstract Fluid Motion Patterns',
    'Vintage Typewriter Mechanism',
    'Circus Tent Interior',
    'Pulsar Star Rotation',
    'Fire Ant Colony Architecture',
    'Foggy Pine Forest Morning',
    'Abstract Watercolor Painting',
    'Cracked Desert Ground Patterns',
    'City Skyscrapers Reflection in Water',
    'Nano-machines'
]

export default async function handler(req, res) {
    let prompt = prompts[Math.floor(Math.random() * prompts.length)]
    res.statusCode = 201;
    res.end(JSON.stringify(prompt));
}
